Repository teknologi-umum/conference, pull requests merged in 2023-09, with the labels that each got.

#34 fix(backend): should acquire request id from response headers
  backend/server.go
Labels: bug

#48 sambal bawang emang mantab sih
  .idea/misc.xml
  backend/csv_reader.go
  backend/main.go
  backend/student-verification-sample.csv
  backend/ticketing.go
  backend/ticketing_test.go
Labels: difficulty: easy

#51 feat: email ticket payment
  backend/config.go
  backend/main.go
  emails/ticket_payment.html
  emails/ticket_payment.txt
  emails/ticket_payment_student_college.html
  emails/ticket_payment_student_college.txt
  emails/ticket_payment_student_highschool.html
  emails/ticket_payment_student_highschool.txt
Labels: difficulty: easy, enhancement

#53 fix: don't specify content-type headers for uploading payment proof
  backend/config.go
  backend/main.go
  backend/server.go
  frontend/package.json
  frontend/pages/pay.vue
  frontend/pnpm-lock.yaml
Labels: bug

#56 fix(backend): name handlebars get overriden
  backend/main.go
Labels: bug

#65 payment confirmation
  emails/payment_success.html
  emails/payment_success.txt
Labels: difficulty: easy, enhancement
